{{- if (not .Values.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-charts.fullname" . }}
  labels:
    {{- include "my-charts.labels" . | nindent 4 }}
type: Opaque
data:
  jupiteroneAccountId: {{ default "" .Values.secrets.jupiteroneAccountId | b64enc | quote }}
  jupiteroneApiKey: {{ default "" .Values.secrets.jupiteroneApiKey | b64enc | quote }}
  jupiteroneIntegrationInstanceId: {{ default "" .Values.secrets.jupiteroneIntegrationInstanceId | b64enc | quote }}
  j1accesstoken: {{ default "" .Values.secrets.j1accesstoken | b64enc | quote }}
  accesskeyid: {{ default "" .Values.secrets.accesskeyid | b64enc | quote }}
  secretaccesskey: {{ default "" .Values.secrets.secretaccesskey | b64enc | quote }}
{{- end }}